events/urls.py
from django.urls import path

from events import views

urlpatterns = [
    path('new_event/', views.new_event, name='new_event'),
    # path('my_meetings/', views.my_meetings, name='my_meetings'),
    path('events_list/', views.events_list, name='event_list'),
    # path('edit/<int:id>', views.meeting_edit, name='meeting_edit'),
    # path('delete/<int:id>', views.meeting_delete, name='meeting_list'),
]

iTexas_v4/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from members import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^special/', views.special, name='special'),
    url(r'^members/', include('members.urls')),
    url(r'^office_hours/', include('office_hours.urls')),
    url(r'^meetings/', include('meetings.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

members/models.py
from audioop import reverse

from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


class MyUserManager(BaseUserManager):
    def create_user(self, podio_code, email, first_name, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not podio_code:
            raise ValueError('Users must have an podio code ID')

        user = self.model(
            email=self.normalize_email(email),
            podio_code=podio_code,
            first_name=first_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, podio_code, email, first_name, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            podio_code,
            email=email,
            first_name=first_name,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    POST = (('lcp', 'LCP'), ('lcvp', 'LCVP'), ('tlb', 'TLB'), ('membro', 'Membro'))
    DEPARTMENT = (
        ('lcp', 'LCP'), ('pm', 'PM'), ('f&l', 'F&L'), ('b2c', 'B2C'), ('b2b', 'B2B'),
        ('oge', 'OGE'), ('ogt', 'OGT'), ('ogv', 'OGV'), ('ige', 'IGE'), ('igt', 'IGT'),)
    email = models.EmailField(verbose_name='E-mail', max_length=255, unique=True)
    podio_code = models.CharField(max_length=10, verbose_name='ID do Podio', unique=True)
    first_name = models.CharField(max_length=20, verbose_name='Nome')
    last_name = models.CharField(max_length=20, verbose_name='Sobrenome')
    post = models.CharField(max_length=10, choices=POST, blank=True, null=True, verbose_name='Cargo')
    department = models.CharField(max_length=10, choices=DEPARTMENT, blank=True, null=True, verbose_name='Área')
    leader = models.ForeignKey("MyUser", blank=True, null=True, on_delete=models.SET_NULL, verbose_name='Líder')
    is_working = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True, verbose_name='Está ativo')
    is_admin = models.BooleanField(default=False, verbose_name='É administrador')
    objects = MyUserManager()

    USERNAME_FIELD = 'podio_code'
    REQUIRED_FIELDS = ['email', 'first_name']

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
{% if user.is_authenticated %}
    <div class="top-bar">
        <h2>iTexas</h2>
        <button class="btn-menu"><i class="fa fa-bars fa-lg"></i></button>
    </div>
    <div class="ogr-container">
    <nav class="menu-mobile">
        <div class="container-close">
            <a class="btn-close">x</a>
        </div>
        <div class="menu-contents">
            <div class="profile-picture"></div>
            <div class="member-infos">
                <a class="member-name" href="{% url 'member_edit' user.podio_code %}">{{ request_user.first_name }} {{ request_user.last_name }}</a>
                <h3 class="member-area">{{ request_user.get_post_display }} de {{ request_user.get_department_display }}</h3>
            </div

            <ul class="function-list">
                {% if user.is_admin %}
                <li><a href="{% url 'member_list' %}" class="button">Lista de Membros</a></li>
                <li><a href="{% url 'officehour_list' %}" class="button">Lista de Office Hours</a></li>
                <li><a href="{% url 'meeting_list' %}" class="button">Lista de Reuniões</a></li>
                <li><a href="{% url 'register' %}" class="button">Cadastrar Novo Membro</a></li>
                {% endif %}
                {% if user.is_working %}
                    <li><a href="{% url 'check' %}" class="button">Check out</a></li>
                {% else %}
                    <li><a href="{% url 'check' %}" class="button">Check in</a></li>
                {% endif %}
                <li><a href="{% url 'event_list' %}" class="button">Calendário de Eventos</a></li>
                <li><a href="{% url 'new_meeting' %}" class="button">Registrar Reunião</a></li>
{#                <li><a href="{% url 'member_edit' user.podio_code %}" class="button">Editar Meu Perfil</a></li> #}
                <li><a href="{% url 'office_hours_history' %}" class="button">Minhas Office Hours</a></li>
                <li><a href="{% url 'my_meetings' %}" class="button">Minhas Reuniões</a></li>
                <li><a href="{% url 'member_report' user.podio_code %}" class="button">Meu Critério de Membresia</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'user_logout' %}">Logout</a></li>
                {% else %}
                    <li><a class="navbar-link" href="{% url 'user_login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="page-body">

    <div class="lateral-menu">
        <div class="logo-area">
            <img class="logo-company" src="../static/images/iTexas.png">
        </div>
        <div class="menu-area">
            <div class="profile-picture"></div>
            <div class="member-infos">
                <a class="member-name" href="{% url 'member_edit' user.podio_code %}">{{ request_user.first_name }} {{ request_user.last_name }}</a>
                <h3 class="member-area">{{ request_user.get_post_display }} de {{ request_user.get_department_display }}</h3>
            </div>
            <ul class="function-list">
                {% if request_user.is_admin %}
                    <li><a href="{% url 'member_list' %}" class="button">Lista de Membros</a></li>
                    <li><a href="{% url 'officehour_list' %}" class="button">Lista de Office Hours</a></li>
                    <li><a href="{% url 'meeting_list' %}" class="button">Lista de Reuniões</a></li>
                    <li><a href="{% url 'register' %}" class="button">Cadastrar Novo Membro</a></li>
                    <li><a href="{% url 'new_event' %}" class="button">Novo Evento</a></li>
                {% endif %}
                {% if user.is_working %}
                    <li><a href="{% url 'check' %}" class="button">Check out</a></li>
                {% else %}
                    <li><a href="{% url 'check' %}" class="button">Check in</a></li>
                {% endif %}
                <li><a href="{% url 'event_list' %}" class="button">Calendário de Eventos</a></li>
                <li><a href="{% url 'new_meeting' %}" class="button">Registrar Reunião</a></li>
{#                <li><a href="{% url 'member_edit' user.podio_code %}" class="button">Editar Meu Perfil</a></li> #}
                <li><a href="{% url 'office_hours_history' %}" class="button">Minhas Office Hours</a></li>
                <li><a href="{% url 'my_meetings' %}" class="button">Minhas Reuniões</a></li>
                <li><a href="{% url 'member_report' user.podio_code %}" class="button">Meu Critério de Membresia</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'user_logout' %}">Logout</a></li>
                {% else %}
                    <li><a class="navbar-link" href="{% url 'user_login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    <div  id="body-content" class="body-content">
        <div class="body-container">
            {% block body_block %}
            {% endblock %}
        </div>
    </div>
{% else %}
    <div class="ogr-container">
        <div class="login-panel">
            <h2 class="title"> Seja bem vindo ao</h2>
            <h2 class="name-app">iTexas!</h2>

            <div class="user-info">
                <form method="post" action="{% url 'user_login' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="podio_code">ID:</label>
                        <input class="input-podio_code form-control" type="text" name="podio_code" placeholder="Podio ID">
                    </div>
                    <div class="form-group">
                        <label for="password">Password:</label>
                        <input class="input-pass form-control" type="password" name="password" placeholder="Password">
                    </div>
                    <div class="button-session">
                        <input type="submit" class="login-button" name="login-button" value="Login">
                        <a class="forgot-pass" href={% url 'reset_password' %} >Esqueci minha senha</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endif %}
</div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.js"
        integrity="sha256-BTlTdQO9/fascB1drekrDVkaKd9PkwBymMlHOiG+qLI=" crossorigin="anonymous"></script>
<script>
    $(".btn-menu").click(function () {
        $(".menu-mobile").show();
        $("#body-content").addClass('active')

    })
    $(".btn-close").click(function () {
        $(".menu-mobile").hide();
        if($("#body-content").hasClass('active')) {
            $("#body-content").removeClass('active')
        }
    })

    jQuery(document).ready(function($) {
        $('.row-office-hours').on('click', function () {
            var id = $(this).attr('id');
            document.location.href = "../edit/"+id;
        });
    });

    jQuery(document).ready(function($) {
        $('.row-member-list').on('click', function () {
            var id = $(this).attr('id');
            document.location.href = "view/"+id;
        });
    });

        jQuery(document).ready(function($) {
        $('.row-meetings').on('click', function () {
            var id = $(this).attr('id');
            document.location.href = "../edit/"+id;
        });
    });

</script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% if user.is_authenticated %}
    {% block body_block %}
        <div class="container">
            <div class="welce">
                {% if user.is_authenticated %}
                    <h1>Olá {{ user.first_name }} {{ user.last_name }},</h1>
                    <h2>Seja bem vindo ao iTexas !</h2>
                {% else %}
                    <h2>Register or Login if you'd like to</h2>
                {% endif %}
            </div>
            <div class="logo-company-content ">
                <img class="logo-company" src="../static/images/texas_vetor.png">
            </div>

        </div>
    {% endblock %}
{% else %}
    <h2>Logar</h2>
{% endif %}

templates/registration.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
    <div class="container">

        {% if registered %}
            <h1>Registrado com Sucesso</h1>
        {% else %}
            <div class="registration-area ogr-container">
                <h1 class="title">Registrar Novo Membro</h1>
                <div class="form-group">
                    <form enctype="multipart/form-data" method="POST">
                        {% csrf_token %}
                        {{ user_form.as_p }}
                        <p class="par-center">
                            <input class="register-button" type="submit" value="Registrar">
                        </p>

                    </form>
                </div>
            </div>

        {% endif %}

    </div>
{% endblock %}

templates/report.html
{% extends "base.html" %}
{% if user.is_authenticated %}
    {% block body_block %}
        <h2 class="member-detail-name">{{ user.first_name  }} {{ user.last_name }}</h2>
        <h3 class="">Critério de Membresia</h3>

        <table class="table">
            <thead class="thead-light">
            <tr>
                <th class="table-column">Mês</th>
                <th class="table-column">Reunião</th>
                <th class="table-column">Office-Hour</th>
                <th class="table-column">Eventos</th>
                <th class="table-column">Resultados</th>
            </tr>
            </thead>
                <tbody>
                <tr class="row-report-table" id="" >
                    <td>Outubro</td>
                    <td><a href="{% url 'my_meetings' %}">83%</a></td>
                    <td><a href="{% url 'office_hours_history' %}">90%</a></td>
                    <td><a href="{% url 'event_list' %}">95%</a></td>
                    <td class="font-success"><a>IDEAL</a></td>
                </tr>

                <tr class="row-report-table" id="" >
                    <td>Novembro</td>
                    <td><a class="link-a" href="{% url 'my_meetings' %}">93%</a></td>
                    <td id="font-danger"><a  class="font-danger" href="{% url 'office_hours_history' %}">60%</a></td>
                    <td><a href="{% url 'event_list' %}">90%</a></td>
                    <td class="font-danger"><a>RISCO</a></td>
                </tr>
                </tbody>
                </table>


    {% endblock %}
{% else %}
    <h2>Logar</h2>
{% endif %}

templates/user_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="ogr-container">
        <div class="login-panel">
            <h2 class="title"> Seja bem vindo ao</h2>
            <h2 class="name-app">iTexas!</h2>

            <div class="user-info">
                <form method="post" action="{% url 'user_login' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="podio_code">ID:</label>
                        <input class="input-podio_code form-control" type="text" name="podio_code" placeholder="Podio ID">
                    </div>
                    <div class="form-group">
                        <label for="password">Password:</label>
                        <input class="input-pass form-control" type="password" name="password" placeholder="Password">
                    </div>
                    {% for message in messages %}
                       <div class="alert alert-danger" id="alert-error">
                           {{ message }}
                       </div>
                   {% endfor %}
                    <div class="button-session">
                        <input type="submit" class="login-button" name="login-button" value="Login">
                        <a class="forgot-pass" href={% url 'reset_password' %}>Esqueci minha senha</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

</body>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script>
    setTimeout(function () {
      document.getElementById("alert-error").style.display = "none";
    }, 3000);
</script>
</html>